[tool.isort]
profile = "black"
known_first_party = "poetry"

[tool.black]
line-length = 79
target-version = ['py311']
exclude = '''
    /(
        \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
    )/
'''
 